### ISSUE TITLE
Add configuration file in YAML

### ISSUE THREAD

**Issue by pradal** [pradal/VersionClimber#6]
The configuration file can be express in YAML.

An example of this file may be:

```yaml
packages:
    - name      : scikit-image
      vcs       : git
      url       : https://github.com/scikit-image/scikit-image
      cmd       : pip install --no-index --no-deps -U
      version   : 0.4
      hierarchy : commit

    - name      : scikit-learn
      vcs       : git
      url       : https://github.com/scikit-learn/scikit-learn
      cmd       : pip install --no-index --no-deps -U
      version   : 0.8
      hierarchy : commit

    - name      : scipy
      vcs       : pypi
      version   : 1.3.0
      hierarchy : minor

    - name      : numpy
      vcs       : pypi
      version   : 0.9.6
      hierarchy : minor

run:
    - python estimate_hog.py
```
